"""Hatchling build hook: bake git provenance into the wheel at build time.

`uv tool install <dir>` builds a wheel and installs it into an isolated,
non-editable venv with no `.git` directory present. If `ao --version` tried
to introspect git at *runtime*, it would find nothing once installed. So the
commit/dirty/tag state must be captured now, at *build* time, and written
into a generated module that ships inside the wheel.
"""

from __future__ import annotations

import subprocess
from datetime import UTC, datetime
from pathlib import Path

from hatchling.builders.hooks.plugin.interface import BuildHookInterface

_GENERATED_HEADER = '"""Auto-generated by hatch_build.py at package-build time. Do not edit."""\n\n'


class BuildInfoHook(BuildHookInterface):
    def initialize(self, version: str, build_data: dict) -> None:
        root = Path(self.root)
        commit = self._git(root, "rev-parse", "--short", "HEAD")
        status = self._git(root, "status", "--porcelain")
        dirty = status != "" if status is not None else None
        tagged = self._git(root, "describe", "--tags", "--exact-match", "HEAD") is not None
        build_time = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")

        out_path = root / "src" / "agent_orchestrator" / "_build_info.py"
        out_path.write_text(
            _GENERATED_HEADER
            + f"BUILD_COMMIT = {commit!r}\n"
            + f"BUILD_DIRTY = {dirty!r}\n"
            + f"BUILD_TAGGED = {tagged!r}\n"
            + f"BUILD_TIME = {build_time!r}\n"
        )
        # Hatchling's default file selection is git-tracked-files-only, so this
        # newly-written (and gitignored) module would otherwise be silently
        # dropped from the wheel. force_include ships it regardless.
        build_data["force_include"][str(out_path)] = "agent_orchestrator/_build_info.py"

    @staticmethod
    def _git(cwd: Path, *args: str) -> str | None:
        try:
            result = subprocess.run(
                ["git", *args],
                cwd=cwd,
                capture_output=True,
                text=True,
                timeout=5,
            )
        except (OSError, subprocess.TimeoutExpired):
            return None
        return result.stdout.strip() if result.returncode == 0 else None
